### ISSUE TITLE
we're worried about you :c

### ISSUE THREAD

**Issue by posaidon09** [tungstengmd/stupid-shit#1]
are you alright?

**Comment by tungstengmd** [comment]
> are you alright?

yeah i'm ok posaidon
just can't use discord

**Comment by tungstengmd** [comment]
you might need to send like a twitter so i can talk to you thru there

**Comment by posaidon09** [comment]
ah i see
sadly i don't have twitter but thank god you're alive

**Comment by tungstengmd** [comment]
yeah i'm alive
haven't killed myself yet but you do need to find a way to contact me before that happens

**Comment by tungstengmd** [comment]
i'm not venting over github so just find a way to contact me

**Comment by posaidon09** [comment]
do you have Signal?

**Comment by tungstengmd** [comment]
sadly no

**Comment by posaidon09** [comment]
damn it
is there another way i can reach you besides twitter?

**Comment by tungstengmd** [comment]
unfortunately not

**Comment by posaidon09** [comment]
hm
hopefully eiriel has it
i told him you're alive but he's offline rn

**Comment by tungstengmd** [comment]
You didn't think I was actually dead, did you?

**Comment by posaidon09** [comment]
no but we were worried that something happened since you just went offline all of a sudden

**Comment by tungstengmd** [comment]
...you sure about that? I'm a bit concerned now. You literally made me type normally.

**Comment by posaidon09** [comment]
we're just happy that you're alright
eiriel already knows since i noticed you were still active here so i told him before opening this issue

**Comment by tungstengmd** [comment]
fair

**Comment by posaidon09** [comment]
actually i'll go make a twitter account real quick
though i'll probably never use it for anything else

**Comment by tungstengmd** [comment]
alr

**Comment by posaidon09** [comment]
i tried signing up 3 times and it gave me this error each time
![image](https://github.com/user-attachments/assets/8d49d743-a344-40bf-8c30-947bb76c07eb)

**Comment by posaidon09** [comment]
i tried signing up 3 times and it gave me this error each time
![image](https://github.com/user-attachments/assets/35130a24-ed21-4802-b2ff-02241d511fb9)

**Comment by tungstengmd** [comment]
can't help try numerous times til it works ig

**Comment by tungstengmd** [comment]
turn dms on
